/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ZipDezip;

import java.util.ArrayList;

/**
 *
 * @author soufiyan
 */
public class HuffmanNode {
    
    //les fils et les parents 
    //list de tout les fils (symboles,Frequences) comparison des frequences 
    //[a ,b ,c ,d ,e ,f ]
    //[12,14,15,16,17,18]
    HuffmanNode fils;
    HuffmanNode parent;
    Node left;
    Node right;
    
    ArrayList<Node> N=new ArrayList<>();
    
    
    public HuffmanNode(){
        
    }
    public static void printCode(HuffmanNode root, String s) 
    { 
  
        // base case; if the left and right are null 
        // then its a leaf node and we print 
        // the code s generated by traversing the tree. 
        if (root.left == null&& root.right== null&& Character.isLetter(root.c)) { 
  
            // c is the character in the node 
            System.out.println(root.c + ":" + s); 
  
            return; 
        } 
  
        // if we go to left then add "0" to the code. 
        // if we go to the right add"1" to the code. 
  
        // recursive calls for left and 
        // right sub-tree of the generated tree. 
        printCode(root.left, s + "0"); 
        printCode(root.right, s + "1"); 
    } 
    
    
}
